spring.kafka.listener.concurrency=1

company-profile.search.group-id=company-profile-search-consumer-itest
company-profile.search.topic=stream-company-profile
company-profile.search.retry-attempts=4
company-profile.search.backoff-delay=100
company-profile.search.autostart.enabled=true
company-profile.search.autocreate.topics=true

management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
management.endpoint.health.probes.enabled=false

chs.api.key=test-api-key
chs.api.url=http://localhost:8888

server.port=${PORT:8080}
wiremock.server.port=8888

logger.namespace=company-profile-search-consumer
